repos:
  - repo: local
    hooks:
      - id: check-all-position
        name: check __all__ position
        entry: python scripts/check_all_position.py
        language: python
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - "--indent=2"
          - "--autofix"
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/crate-ci/typos
    rev: v1.46.0
    hooks:
      - id: typos

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.8
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-format
      - id: ruff-check
        args:
          - --fix
          - --unsafe-fixes

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.2
    hooks:
      - id: mypy
        additional_dependencies:
          - aiohttp>=3.12,<4
          - faker>=33
          - foghttp>=0.1.3,<0.2
          - httpx>=0.28,<1
          - jinja2>=3.1,<4
          - psutil>=6,<8
          - typer>=0.16,<1
          - zapros>=0.11,<1
        args:
          - --config-file=pyproject.toml
          - --install-types
          - --non-interactive
        files: ^foghttp_benchmark/.*\.pyi?$
